export const dataTypes = ["Article", "Upload"];
export const qc1Array = ["Yes", "No", "All"];

export const continents = [
  "Africa",
  "Antarctica",
  "Asia",
  "Europe",
  "North America",
  "Australia (Oceania)",
  "South America",
];
export const countriesByContinent = [
  {
    continent: "Africa",
    countries: [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cameroon",
      "Cape Verde",
      "Chad",
      "Comoros",
    ],
  },
  {
    continent: "Antarctica",
    countries: ["Antarctica (No permanent residents)"],
  },
  {
    continent: "Asia",
    countries: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "Cyprus",
    ],
  },
  {
    continent: "Europe",
    countries: [
      "Albania",
      "Andorra",
      "Austria",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Czech Republic",
      "Denmark",
    ],
  },
  {
    continent: "North America",
    countries: [
      "Canada",
      "United States",
      "Mexico",
      "Belize",
      "Costa Rica",
      "El Salvador",
      "Guatemala",
      "Honduras",
      "Nicaragua",
      "Panama",
    ],
  },
  {
    continent: "Australia (Oceania)",
    countries: [
      "Australia",
      "Fiji",
      "New Zealand",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "Palau",
      "Papua New Guinea",
      "Samoa",
    ],
  },
  {
    continent: "South America",
    countries: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
    ],
  },
];

export const spokenLanguages = [
  { name: "Hindi", code: "hn" },
  { name: "Bengali", code: "bn" },
  { name: "Telugu", code: "te" },
  { name: "Marathi", code: "mr" },
  { name: "Tamil", code: "ta" },
  { name: "Urdu", code: "ur" },
  { name: "Gujarati", code: "gu" },
  { name: "Kannada", code: "kn" },
  { name: "Odia", code: "or" },
  { name: "Punjabi", code: "pa" },
  { name: "Malayalam", code: "ml" },
  { name: "Assamese", code: "as" },
  { name: "Maithili", code: "mai" },
  { name: "Sanskrit", code: "sa" },
  { name: "Kashmiri", code: "ks" },
  { name: "Nepali", code: "ne" },
  { name: "Konkani", code: "kok" },
  { name: "Sindhi", code: "sd" },
  { name: "Dogri", code: "doi" },
  { name: "Manipuri", code: "mni" },
  { name: "Bodo", code: "brx" },
  { name: "Santali", code: "sat" },
  { name: "Khasi", code: "kha" },
];
